server:
  port: 8081

datafiles:
  access2: "datafiles/access2.yml"
  access3: "datafiles/access3.yml"
  accounts: "datafiles/accounts.yml"
  balances: "datafiles/balances.yml"
  clients: "datafiles/clients.yml"
  contacts: "datafiles/contacts.yml"
  operations: "datafiles/operations.yml"